# Generated by Django 4.1.6 on 2023-02-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_Verbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_langue', models.CharField(max_length=50)),
                ('regle_conjugaison', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temps_Verbaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_temps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_verbe', models.CharField(max_length=50)),
                ('Classe_Verbe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.classe_verbe')),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Etre_conjuguer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=25)),
                ('person2', models.CharField(max_length=25)),
                ('person3', models.CharField(max_length=25)),
                ('person4', models.CharField(max_length=25)),
                ('person5', models.CharField(max_length=25)),
                ('person6', models.CharField(max_length=25)),
                ('Langue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.langue')),
                ('Temps_Verbaux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.temps_verbaux')),
                ('Verbe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.verbe')),
            ],
        ),
        migrations.AddField(
            model_name='classe_verbe',
            name='Langue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.langue'),
        ),
        migrations.CreateModel(
            name='Avoir_regle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regle', models.CharField(max_length=50)),
                ('Langue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.langue')),
                ('Temps_Verbaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conjugaison_api1.temps_verbaux')),
            ],
        ),
    ]
