# Generated by Django 4.1.6 on 2023-02-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugaison_api1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etre_conjuguer',
            name='audio',
            field=models.ImageField(blank=True, upload_to='Documents/'),
        ),
    ]
